import "../styles/globals.css";
import TodoProvider from "@/context/TodoContext";
import fetchTodos from "./lib/fetchTodos";

export const metadata = {
	title: "Next Todo App",
	description: "Generated by next app",
};

export default async function RootLayout({ children }) {
	const initialTodos = await fetchTodos();
	return (
		<html lang="en">
			<head>
				<link rel="icon" href="/favicon.ico" sizes="any" />
				<link rel="icon" href="/favicon.svg" type="image/svg+xml" />
			</head>
			<body>
				<TodoProvider initialTodos={initialTodos}>{children}</TodoProvider>
			</body>
		</html>
	);
}
